# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_text',
            new_name='text',
        ),
    ]
